version: '3.6'

networks:
  project:
    driver: bridge
  proxy:
    external:
      name: umanit

services:
  php:
    image: umanit/web:7.0
    restart: on-failure
    volumes:
      - .:/var/www/html:cached
      - ./logs/php:/var/log/php:cached
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
    environment:
        SYMFONY__ENV: dev
    networks:
      - project

  nginx:
    image: nginx:1-alpine
    restart: on-failure
    depends_on:
      - php
    volumes:
      - .:/var/www/html:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx:cached
    networks:
      - project
      - proxy
    ports:
      - "5000:80"
